use crate::ciphers::feistel::cipher::{feistel_decrypt, feistel_encrypt};
use crate::ciphers::feistel::keys::feistel_default_key;
use crate::core::errors::CipherError;
use crate::core::sample::sample_bytes;

/// Round-trip generated bytes and insist the ciphertext actually
/// differs from the plaintext.
pub fn feistel_verify() -> Result<bool, CipherError> {
    let data = sample_bytes(256);
    let key = feistel_default_key();
    let sealed = feistel_encrypt(&data, key);
    if sealed == data {
        return Err(CipherError::BadKey("keystream left input unchanged"));
    }
    let opened = feistel_decrypt(&sealed, key);
    Ok(opened == data)
}
