use crate::ciphers::speck::cipher::{speck_decrypt, speck_encrypt};
use crate::ciphers::speck::keys::speck_default_key;
use crate::core::errors::CipherError;
use crate::core::sample::sample_bytes;

/// Round-trip generated bytes and insist the ciphertext actually
/// differs from the plaintext.
pub fn speck_verify() -> Result<bool, CipherError> {
    let data = sample_bytes(256);
    let key = speck_default_key();
    let sealed = speck_encrypt(&data, key);
    if sealed == data {
        return Err(CipherError::BadKey("keystream left input unchanged"));
    }
    let opened = speck_decrypt(&sealed, key);
    Ok(opened == data)
}
