use crate::ciphers::xor_stream::cipher::{xor_stream_decrypt, xor_stream_encrypt};
use crate::ciphers::xor_stream::keys::xor_stream_default_key;
use crate::core::errors::CipherError;
use crate::core::sample::sample_bytes;

/// Round-trip generated bytes and insist the ciphertext actually
/// differs from the plaintext.
pub fn xor_stream_verify() -> Result<bool, CipherError> {
    let data = sample_bytes(256);
    let key = xor_stream_default_key();
    let sealed = xor_stream_encrypt(&data, key);
    if sealed == data {
        return Err(CipherError::BadKey("keystream left input unchanged"));
    }
    let opened = xor_stream_decrypt(&sealed, key);
    Ok(opened == data)
}
