use crate::ciphers::lcg_stream::cipher::{lcg_stream_decrypt, lcg_stream_encrypt};
use crate::ciphers::lcg_stream::keys::lcg_stream_default_key;
use crate::core::errors::CipherError;
use crate::core::sample::sample_bytes;

/// Round-trip generated bytes and insist the ciphertext actually
/// differs from the plaintext.
pub fn lcg_stream_verify() -> Result<bool, CipherError> {
    let data = sample_bytes(256);
    let key = lcg_stream_default_key();
    let sealed = lcg_stream_encrypt(&data, key);
    if sealed == data {
        return Err(CipherError::BadKey("keystream left input unchanged"));
    }
    let opened = lcg_stream_decrypt(&sealed, key);
    Ok(opened == data)
}
