use crate::ciphers::tea::cipher::{tea_decrypt, tea_encrypt};
use crate::ciphers::tea::keys::tea_default_key;
use crate::core::errors::CipherError;
use crate::core::sample::sample_bytes;

/// Round-trip generated bytes and insist the ciphertext actually
/// differs from the plaintext.
pub fn tea_verify() -> Result<bool, CipherError> {
    let data = sample_bytes(256);
    let key = tea_default_key();
    let sealed = tea_encrypt(&data, key);
    if sealed == data {
        return Err(CipherError::BadKey("keystream left input unchanged"));
    }
    let opened = tea_decrypt(&sealed, key);
    Ok(opened == data)
}
