use crate::ciphers::simon::cipher::{simon_decrypt, simon_encrypt};
use crate::ciphers::simon::keys::simon_default_key;
use crate::core::errors::CipherError;
use crate::core::sample::sample_bytes;

/// Round-trip generated bytes and insist the ciphertext actually
/// differs from the plaintext.
pub fn simon_verify() -> Result<bool, CipherError> {
    let data = sample_bytes(256);
    let key = simon_default_key();
    let sealed = simon_encrypt(&data, key);
    if sealed == data {
        return Err(CipherError::BadKey("keystream left input unchanged"));
    }
    let opened = simon_decrypt(&sealed, key);
    Ok(opened == data)
}
