use crate::ciphers::rc4::cipher::{rc4_decrypt, rc4_encrypt};
use crate::ciphers::rc4::keys::rc4_default_key;
use crate::core::errors::CipherError;
use crate::core::sample::sample_bytes;

/// Round-trip generated bytes and insist the ciphertext actually
/// differs from the plaintext.
pub fn rc4_verify() -> Result<bool, CipherError> {
    let data = sample_bytes(256);
    let key = rc4_default_key();
    let sealed = rc4_encrypt(&data, key);
    if sealed == data {
        return Err(CipherError::BadKey("keystream left input unchanged"));
    }
    let opened = rc4_decrypt(&sealed, key);
    Ok(opened == data)
}
