use crate::ciphers::salsa_lite::cipher::{salsa_lite_decrypt, salsa_lite_encrypt};
use crate::ciphers::salsa_lite::keys::salsa_lite_default_key;
use crate::core::errors::CipherError;
use crate::core::sample::sample_bytes;

/// Round-trip generated bytes and insist the ciphertext actually
/// differs from the plaintext.
pub fn salsa_lite_verify() -> Result<bool, CipherError> {
    let data = sample_bytes(256);
    let key = salsa_lite_default_key();
    let sealed = salsa_lite_encrypt(&data, key);
    if sealed == data {
        return Err(CipherError::BadKey("keystream left input unchanged"));
    }
    let opened = salsa_lite_decrypt(&sealed, key);
    Ok(opened == data)
}
