use crate::ciphers::xtea::cipher::{xtea_decrypt, xtea_encrypt};
use crate::ciphers::xtea::keys::xtea_default_key;
use crate::core::errors::CipherError;
use crate::core::sample::sample_bytes;

/// Round-trip generated bytes and insist the ciphertext actually
/// differs from the plaintext.
pub fn xtea_verify() -> Result<bool, CipherError> {
    let data = sample_bytes(256);
    let key = xtea_default_key();
    let sealed = xtea_encrypt(&data, key);
    if sealed == data {
        return Err(CipherError::BadKey("keystream left input unchanged"));
    }
    let opened = xtea_decrypt(&sealed, key);
    Ok(opened == data)
}
